apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-pre
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: system-gitops-pre
  sources:
    # Chart from Chart Repo
    - chart: external-secrets
      repoURL: https://charts.external-secrets.io
      targetRevision: 0.16.2
      helm:
        # https://argo-cd.readthedocs.io/en/stable/user-guide/multiple_sources/#helm-value-files-from-external-git-repository
        valueFiles:
          - $values/manifests/pre/add-ons/external-secrets/values.yaml
    # Values from Git https://akuity.io/blog/argo-cd-helm-values-files/
    - repoURL: 'https://dev.azure.com/Standard-Insurance/CAT-Enterprise-AKS/_git/argo-system-apps'
      targetRevision: HEAD
      ref: values
  destination:
    name: in-cluster
    namespace: external-secrets
  # Sync policy
  syncPolicy:
    automated:
      # Automated sync by default retries failed attempts 5 times with following delays between attempts (5s, 10s, 20s, 40s, 80s); retry controlled using `retry` field.
      prune: true # Specifies if resources should be pruned during auto-syncing (false by default).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected (false by default).
